imports:
- path: overall.yaml
- path: project.tmpl.yaml
  data:
    PROJECT_ID: example-prod
    SUFFIX: prod
    AUDIT_DATASET_NAME: example_prod_logs
    STATE_BUCKET_NAME: example-prod-state

# Only create central projects for prod.
devops:
  project:
    project_id: example-devops
    owners_group: example-devops-owners@example.com
    auditors_group: example-auditors@example.com
    audit:
      logs_bigquery_dataset:
        dataset_id: devops_audit_logs
        location: US
    devops:
      state_storage_bucket:
        name: example-devops-state
        location: US

audit_logs_project:
  project_id: example-audit
  owners_group: example-audit-owners@example.com
  auditors_group: example-auditors@example.com
  audit:
    logs_bigquery_dataset:
      dataset_id: example_audit_logs
      location: US
  devops:
    state_storage_bucket:
      name: example-audit-state
      location: US

forseti:
  project:
    project_id: example-forseti
    owners_group: example-forseti-owners@example.com
    auditors_group: example-auditors@example.com
    audit:
      logs_bigquery_dataset:
        dataset_id: example_forseti_logs
        location: US
    devops:
      state_storage_bucket:
        name: example-forseti-state
        location: US
    # Setup NAT to allow private forseti to access the internet to fetch the Forseti repo while
    # having no external IP.
    # See https://github.com/forseti-security/terraform-google-forseti/issues/234.
    terraform_deployments:
      resources:
        config:
          resource:
          - google_compute_router:
              forseti-router:
                name: forseti-router
                project: example-forseti
                network: default
                region: us-central1
          - google_compute_router_nat:
              forseti-nat:
                name: forseti-nat
                project: example-forseti
                region: us-central1
                nat_ip_allocate_option: AUTO_ONLY
                source_subnetwork_ip_ranges_to_nat: ALL_SUBNETWORKS_ALL_IP_RANGES
                router: ${google_compute_router.forseti-router.name}
  properties:
    client_enabled: false
    server_private: true
    cloudsql_private: true
