projects:
- project_id: ruihuang-dtthn171-project1  # Data-hosting project.
  owners_group: ruihuang_owner@google.com
  auditors_group: ruihuang_audit@google.com
  data_readwrite_groups:
  - ruihuang_test1@google.com
  data_readonly_groups:
  - ruihuang_test2@google.com
  - ruihuang_test3@google.com
  bigquery_datasets:
  - name: us_data
    location: US
    additional_dataset_permissions:
      readwrite:
      - group:ruihuang_test4@google.com
  data_buckets:
  - name_suffix: -bucket111
    location: ASIA-SOUTHEAST1
    storage_class: REGIONAL
  - name_suffix: -bucket222
    location: ASIA-SOUTHEAST1
    storage_class: REGIONAL
    additional_bucket_permissions:
      readonly:
      - group:ruihuang_test5@google.com
  - name_suffix: -bucket333
    location: ASIA-SOUTHEAST1
    storage_class: REGIONAL
  stackdriver_alert_email: ruihuang@google.com
  audit_logs:
    logs_gcs_bucket:
      # Naming convention: ${AUDIT_LOGS_PROJECT_ID}-${PROJECT_ID}
      name: ruihuang-dtthn171-audit-logs-ruihuang-dtthn171-project1
      location: ASIA-SOUTHEAST1
      storage_class: REGIONAL
      ttl_days: 365
    logs_bigquery_dataset:
      # Naming convention: PROJECT_ID, with underscores instead of dashes.
      name: ruihuang_dtthn171_data_project
      location: US
